### PR TITLE
Command line parameter profile switching

### PR DESCRIPTION
**Pull request by Snoothy**
I have implemented CLI profile switching and updated the documentation. The profile switching is using RPC to existing instances of UCR.

### CODE REVIEW

**Comment by evilC** [comment]
Why SingleInstance Off?  
I am wondering if there is maybe a better way to do this, I may have to ask HotkeyIt...  
Taking the time to knock up some code is appreciated though :)

**Comment by Snoothy** [comment]
SingleInstance has to be turned in order for the script to run its initial part for profile changing. The script will still exit if another instance is present. This is checked with the "remoteUCR".

**Comment by evilC** [comment]
Could we maybe not move this part out into a separate file?  
I would rather leave `#SingleInstance` on

**Comment by Snoothy** [comment]
I have extracted the command line functionality out into its own file now and reverted SingleInstance to force.

**Pull request merged**
