### PR TITLE
Extent deadzones

### PR DESCRIPTION
**Pull request by StrikeEagleCC**

### CODE REVIEW

**Comment by StrikeEagleCC** [comment]
Didn't know what I was doing. Sorry for the clutter.

**Comment by evilC** [comment]
Not sure what is going on here, do you actually wanna merge in?  
Regarding the replacement `DeadZone` function, if adding these new parameters it would probably make sense to make the new parameters have defaults, so something like this maybe?  
`Deadzone(value, dzp, ldzp := 0, hdzp := 100){`  
By the way, please feel free to join us in the Discord chat channel - https://discord.gg/MmnhQYQ

**Comment by evilC** [comment]
We have an awesome little discussion going on in the [UCR Thread](https://autohotkey.com/boards/viewtopic.php?p=194014#p194014) which initially was about remapping detent positions, but seems to have evolved into something which could replace the deadzone system with something much more sophisticated. Check it out, I think it may serve your needs also.

**Comment by StrikeEagleCC** [comment]
This pull request was a result of not understanding github--I was trying to learn how to use it, and intended to create a pull request for myself and didn't realize it defaulted to your master branch. Once I figured out what I was doing, I created the other pull request you see, which was deliberate.

As I mentioned in the other request, I'm not a programmer. I know just enough to modify simple things for purposes. After seeing the breakpoint example you were discussing with Oliver on the AHK forum, I figured I could solve my own problem. Once I did, I thought it might be useful to you, and github seemed like the easiest way to share with you what I did.

The remainder of this comment may be a mute point, given the discussions about breakpoint mapping happening now, but for the sake of completeness, I'll continue. I didn't realize I could define variables as you've done in your first comment--would that eliminate the need to modify all the plugins to provide  the extra arguments? Also, as I've implemented it, the deadzone values represent a percentage of the range, not a position on the range, so `Deadzone(value, dzp, ldzp := 0, hdzp := 0){` would be more appropriate.

No need to reply here unless you feel particularly moved. I'll monitor the AHK thread. Thanks for the discord invite.

**Pull request closed without merging**
